### PR TITLE
Introduce Bitmap for drawing on DrawContext

### PR DESCRIPTION
**Pull request by ababo**
This commit contains the following changes:
1. The project has been moved to golang modules.
2. Added Bitmap type (for Darwin and Windows).
3. Removed the previous code for image drawing.

### CODE REVIEW

**Comment by ghost** [comment]
No issues found.
Wouldn't it make sense to have `Image` or `Bitmap` method fro context in golang for consistency. Similar to other primitives to draw?

**Comment by ababo** [comment]
@RustamGamidov It's not supported in general case (especially the pixel access) without excessive complications. IMO it's not a problem, since `Bitmap` doesn't pretend to be an image, it's more a platform-depending graphic resource.

**Comment by ghost** [comment]
Yes it's not problem, just a consistent interface to use

**Review by ghost — APPROVED** [review]
no issues found

**Pull request merged**
